# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.inmetro.com:
    container_name: orderer.inmetro.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/inmetro.com/orderers/orderer.inmetro.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/inmetro.com/orderers/orderer.inmetro.com/tls/:/var/hyperledger/orderer/tls
        - orderer.inmetro.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.inmetro.com:
    container_name: peer0.inmetro.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.inmetro.com
      - CORE_PEER_ADDRESS=peer0.inmetro.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.inmetro.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.inmetro.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.inmetro.com:7051
      - CORE_PEER_LOCALMSPID=InmetroMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/inmetro.com/peers/peer0.inmetro.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/inmetro.com/peers/peer0.inmetro.com/tls:/etc/hyperledger/fabric/tls
        - peer0.inmetro.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.inmetro.com:
    container_name: peer1.inmetro.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.inmetro.com
      - CORE_PEER_ADDRESS=peer1.inmetro.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.inmetro.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.inmetro.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.inmetro.com:7051
      - CORE_PEER_LOCALMSPID=InmetroMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/inmetro.com/peers/peer1.inmetro.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/inmetro.com/peers/peer1.inmetro.com/tls:/etc/hyperledger/fabric/tls
        - peer1.inmetro.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.nanoBusiness.com:
    container_name: peer0.nanoBusiness.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.nanoBusiness.com
      - CORE_PEER_ADDRESS=peer0.nanoBusiness.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.nanoBusiness.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.nanoBusiness.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nanoBusiness.com:9051
      - CORE_PEER_LOCALMSPID=NanoBusinessMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/nanoBusiness.com/peers/peer0.nanoBusiness.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/nanoBusiness.com/peers/peer0.nanoBusiness.com/tls:/etc/hyperledger/fabric/tls
        - peer0.nanoBusiness.com:/var/hyperledger/production

    ports:
      - 9051:9051
      
  peer1.nanoBusiness.com:
    container_name: peer1.nanoBusiness.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.nanoBusiness.com
      - CORE_PEER_ADDRESS=peer1.nanoBusiness.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.nanoBusiness.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.nanoBusiness.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nanoBusiness.com:9051
      - CORE_PEER_LOCALMSPID=NanoBusinessMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/nanoBusiness.com/peers/peer1.nanoBusiness.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/nanoBusiness.com/peers/peer1.nanoBusiness.com/tls:/etc/hyperledger/fabric/tls
        - peer1.nanoBusiness.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.ird.com:
    container_name: peer0.ird.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.ird.com
      - CORE_PEER_ADDRESS=peer0.ird.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ird.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ird.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ird.com:11051
      - CORE_PEER_LOCALMSPID=IrdMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ird.com/peers/peer0.ird.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ird.com/peers/peer0.ird.com/tls:/etc/hyperledger/fabric/tls
        - peer0.ird.com:/var/hyperledger/production
    ports:
      - 11051:11051
      
  peer1.ird.com:
    container_name: peer0.ird.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.ird.com
      - CORE_PEER_ADDRESS=peer1.ird.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.ird.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.ird.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.ird.com:11051
      - CORE_PEER_LOCALMSPID=IrdMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ird.com/peers/peer1.ird.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ird.com/peers/peer1.ird.com/tls:/etc/hyperledger/fabric/tls
        - peer1.ird.com:/var/hyperledger/production
    ports:
      - 12051:12051
